### ISSUE TITLE
ng-gallery not working with Angular@15.2.X

### ISSUE THREAD

**Issue by germainperdigal** [MurhafSousli/ngx-gallery#581]
Hi there,

Tried to install ng-gallery (tried @9.0.1 and latest), but no way to make it work with Angular 15.2.X.

Here is my stack :
`"dependencies": {
    "@angular/animations": "^15.2.9",
    "@angular/cdk": "^15.2.9",
    "@angular/common": "^15.2.0",
    "@angular/compiler": "^15.2.0",
    "@angular/core": "^15.2.0",
    "@angular/forms": "^15.2.0",
    "@angular/material": "^15.2.9",
    "@angular/platform-browser": "^15.2.0",
    "@angular/platform-browser-dynamic": "^15.2.0",
    "@angular/router": "^15.2.0",
    "@auth0/angular-jwt": "^5.1.2",
    "@types/quill": "^1.3.10",
    "ng-gallery": "^9.0.1",
    "ngx-pagination": "^6.0.3",
    "ngx-quill": "^21.0.0",
    "ngx-toastr": "^16.2.0",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.12.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^15.2.6",
    "@angular/cli": "~15.2.6",
    "@angular/compiler-cli": "^15.2.0",
    "@types/jasmine": "~4.3.0",
    "autoprefixer": "^10.4.14",
    "jasmine-core": "~4.5.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.0.0",
    "postcss": "^8.4.24",
    "tailwindcss": "^3.3.2",
    "typescript": "~4.9.4"
  }`

Here is the error I got using 9.0.1 :

` node_modules/ng-gallery/lib/components/gallery-core.component.d.ts:38:89 - error TS2344: Type '{ galleryId: { alias: "galleryId"; required: false; }; state: { alias: "state"; required: false; }; config: { alias: "config"; required: false; }; }' does not satisfy the constraint '{ [key: string]: string; }'.
  Property '"galleryId"' is incompatible with index signature.
    Type '{ alias: "galleryId"; required: false; }' is not assignable to type 'string'.

38     static ɵcmp: i0.ɵɵComponentDeclaration<GalleryCoreComponent, "gallery-core", never, { "galleryId": { "alias": "galleryId"; "required": false; }; "state": { "alias": "state"; "required": false; }; "config": { "alias": "config"; "required": false; }; }, { "itemClick": "itemClick"; "thumbClick": "thumbClick"; "error": "error"; }, never, never, false, never>;
                                                                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/ng-gallery/lib/components/gallery-counter.component.d.ts:6:95 - error TS2344: Type '{ state: { alias: "state"; required: false; }; }' does not satisfy the constraint '{ [key: string]: string; }'.
  Property '"state"' is incompatible with index signature.
    Type '{ alias: "state"; required: false; }' is not assignable to type 'string'.

6     static ɵcmp: i0.ɵɵComponentDeclaration<GalleryCounterComponent, "gallery-counter", never, { "state": { "alias": "state"; "required": false; }; }, {}, never, never, false, never>;
` 

Any idea ? Tried to reproduce this Stackblitz but nothing works... https://stackblitz.com/edit/ngx-gallery-5rmee4?file=package.json

**Comment by MurhafSousli** [comment]
For Angular 15, use ng-gallery@8.0.4 https://github.com/MurhafSousli/ngx-gallery/blob/master/CHANGELOG.md#804
